// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.6
// source: aiProompt.proto

package aiProompt

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProomptMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ProomptMsg) Reset() {
	*x = ProomptMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aiProompt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProomptMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProomptMsg) ProtoMessage() {}

func (x *ProomptMsg) ProtoReflect() protoreflect.Message {
	mi := &file_aiProompt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProomptMsg.ProtoReflect.Descriptor instead.
func (*ProomptMsg) Descriptor() ([]byte, []int) {
	return file_aiProompt_proto_rawDescGZIP(), []int{0}
}

func (x *ProomptMsg) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ProomptReturn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ProomptReturn) Reset() {
	*x = ProomptReturn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aiProompt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProomptReturn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProomptReturn) ProtoMessage() {}

func (x *ProomptReturn) ProtoReflect() protoreflect.Message {
	mi := &file_aiProompt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProomptReturn.ProtoReflect.Descriptor instead.
func (*ProomptReturn) Descriptor() ([]byte, []int) {
	return file_aiProompt_proto_rawDescGZIP(), []int{1}
}

func (x *ProomptReturn) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_aiProompt_proto protoreflect.FileDescriptor

var file_aiProompt_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x61, 0x69, 0x50, 0x72, 0x6f, 0x6f, 0x6d, 0x70, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x61, 0x69, 0x50, 0x72, 0x6f, 0x6f, 0x6d, 0x70, 0x74, 0x22, 0x26, 0x0a, 0x0a,
	0x50, 0x72, 0x6f, 0x6f, 0x6d, 0x70, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x29, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x6f, 0x6d, 0x70, 0x74, 0x52,
	0x65, 0x74, 0x75, 0x72, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32,
	0x50, 0x0a, 0x09, 0x61, 0x69, 0x50, 0x72, 0x6f, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x43, 0x0a, 0x10,
	0x48, 0x65, 0x61, 0x6c, 0x74, 0x63, 0x61, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x6f, 0x6d, 0x70, 0x74,
	0x12, 0x15, 0x2e, 0x61, 0x69, 0x50, 0x72, 0x6f, 0x6f, 0x6d, 0x70, 0x74, 0x2e, 0x50, 0x72, 0x6f,
	0x6f, 0x6d, 0x70, 0x74, 0x4d, 0x73, 0x67, 0x1a, 0x18, 0x2e, 0x61, 0x69, 0x50, 0x72, 0x6f, 0x6f,
	0x6d, 0x70, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x6f, 0x6d, 0x70, 0x74, 0x52, 0x65, 0x74, 0x75, 0x72,
	0x6e, 0x42, 0x13, 0x5a, 0x11, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x61, 0x69, 0x50,
	0x72, 0x6f, 0x6f, 0x6d, 0x70, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_aiProompt_proto_rawDescOnce sync.Once
	file_aiProompt_proto_rawDescData = file_aiProompt_proto_rawDesc
)

func file_aiProompt_proto_rawDescGZIP() []byte {
	file_aiProompt_proto_rawDescOnce.Do(func() {
		file_aiProompt_proto_rawDescData = protoimpl.X.CompressGZIP(file_aiProompt_proto_rawDescData)
	})
	return file_aiProompt_proto_rawDescData
}

var file_aiProompt_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_aiProompt_proto_goTypes = []interface{}{
	(*ProomptMsg)(nil),    // 0: aiProompt.ProomptMsg
	(*ProomptReturn)(nil), // 1: aiProompt.ProomptReturn
}
var file_aiProompt_proto_depIdxs = []int32{
	0, // 0: aiProompt.aiProompt.HealtcareProompt:input_type -> aiProompt.ProomptMsg
	1, // 1: aiProompt.aiProompt.HealtcareProompt:output_type -> aiProompt.ProomptReturn
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aiProompt_proto_init() }
func file_aiProompt_proto_init() {
	if File_aiProompt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aiProompt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProomptMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aiProompt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProomptReturn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aiProompt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aiProompt_proto_goTypes,
		DependencyIndexes: file_aiProompt_proto_depIdxs,
		MessageInfos:      file_aiProompt_proto_msgTypes,
	}.Build()
	File_aiProompt_proto = out.File
	file_aiProompt_proto_rawDesc = nil
	file_aiProompt_proto_goTypes = nil
	file_aiProompt_proto_depIdxs = nil
}
